services:
  # 1. Servicio para el frontend (React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      
    container_name: medcore-frontend
    image: medcore-frontend
    ports:
      - "8080:80"
